-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 7.5
-- Tue Mar 02 13:32:23 2021

-- parameterized module component declaration
component ram_i2c
    port (DataInA: in  std_logic_vector(15 downto 0); 
        DataInB: in  std_logic_vector(7 downto 0); 
        AddressA: in  std_logic_vector(3 downto 0); 
        AddressB: in  std_logic_vector(4 downto 0); 
        ClockA: in  std_logic; ClockB: in  std_logic; 
        ClockEnA: in  std_logic; ClockEnB: in  std_logic; 
        WrA: in  std_logic; WrB: in  std_logic; ResetA: in  std_logic; 
        ResetB: in  std_logic; QA: out  std_logic_vector(15 downto 0); 
        QB: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : ram_i2c
    port map (DataInA(15 downto 0)=>__, DataInB(7 downto 0)=>__, 
        AddressA(3 downto 0)=>__, AddressB(4 downto 0)=>__, ClockA=>__, 
        ClockB=>__, ClockEnA=>__, ClockEnB=>__, WrA=>__, WrB=>__, ResetA=>__, 
        ResetB=>__, QA(15 downto 0)=>__, QB(7 downto 0)=>__);
